export const DEFAULT_FIELDS = {
  ACCOUNT_LIST: 'id,name,account_id,account_status,currency,timezone_name,business_name',
  ACCOUNT_INFO: 'id,name,account_id,account_status,age,currency,timezone_name,timezone_offset_hours_utc,business_name,business_city,business_country_code,spend_cap,amount_spent,balance,owner,funding_source_details,disable_reason,created_time',
  CAMPAIGN_LIST: 'id,name,objective,status,effective_status,daily_budget,lifetime_budget,budget_remaining,buying_type,bid_strategy,special_ad_categories,created_time,updated_time',
  CAMPAIGN_GET: 'id,name,objective,status,effective_status,daily_budget,lifetime_budget,budget_remaining,buying_type,bid_strategy,special_ad_categories,spend_cap,start_time,stop_time,created_time,updated_time',
  ADSET_LIST: 'id,name,campaign_id,status,effective_status,daily_budget,lifetime_budget,budget_remaining,bid_amount,bid_strategy,billing_event,optimization_goal,targeting,promoted_object,start_time,end_time,created_time,updated_time',
  AD_LIST: 'id,name,adset_id,campaign_id,status,effective_status,creative,tracking_specs,conversion_specs,created_time,updated_time,preview_shareable_link',
  CREATIVE_LIST: 'id,name,status,object_story_spec,thumbnail_url,image_url,url_tags,asset_feed_spec',
  CREATIVE_GET: 'id,name,status,object_story_spec,thumbnail_url,image_url,url_tags,asset_feed_spec,body,title,link_url,call_to_action_type',
  IMAGE_LIST: 'id,hash,name,url,url_128,width,height,created_time,status',
  VIDEO_LIST: 'id,title,description,length,created_time,updated_time,status,thumbnails,permalink_url',
  VIDEO_GET: 'id,title,description,length,source,created_time,updated_time,status,thumbnails,permalink_url,embeddable,format',
  AUDIENCE_LIST: 'id,name,subtype,description,approximate_count,delivery_status,operation_status,time_created,time_updated',
  INSIGHTS: 'impressions,clicks,spend,cpc,cpm,ctr,actions',
  PIXEL_LIST: 'id,name,code,creation_time,last_fired_time',
  PIXEL_GET: 'id,name,code,creation_time,last_fired_time,owner_ad_account,owner_business,data_use_setting,is_unavailable,automatic_matching_fields',
  LEADFORM_LIST: 'id,name,status,created_time,leads_count',
  LEAD_LIST: 'id,created_time,field_data',
  RULE_LIST: 'id,name,status,evaluation_spec,execution_spec,schedule_spec,created_time,updated_time',
  LABEL_LIST: 'id,name,created_time,updated_time',
  SAVED_AUDIENCE_LIST: 'id,name,description,targeting,approximate_count,run_status,sentence_lines',
  ACTIVITY_LIST: 'event_type,event_time,actor_name,actor_id,object_id,object_type,extra_data,translated_event_type',
  CUSTOM_CONVERSION_LIST: 'id,name,pixel,custom_event_type,rule,default_conversion_value,creation_time,last_fired_time,is_archived',
  CUSTOM_CONVERSION_GET: 'id,name,pixel,custom_event_type,rule,default_conversion_value,creation_time,last_fired_time,is_archived,first_fired_time,account_id,description,event_source_type',
  BUDGET_SCHEDULE: 'id,budget_value,budget_value_type,time_start,time_end,recurrence_type,status',
} as const;
